### ISSUE TITLE
robot-master needs monitoring, possibly operational documentation

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss-deprecated/robot-master#67]
We apparently do not have monitoring in place for this process that should be continuously running, and the method for restarting it seems to be some shared knowledge among the right individuals but not necessarily recorded in a common place (this is anecdotal, not sure of the state of this).

Will need to establish service policy ... proposing next-day response rather than 24/7.  Would like this to include weekends to avoid workflow backlog and accommodate work that is scheduled for weekends. Weekend response could reasonably be limited to simple restarts unless monitoring itself includes some attempts at auto-restart.

Alerts from monitoring should go to workflow-services-alerts@lists.stanford.edu

**Comment by blalbrit** [comment]
@LynnMcRae I'll handle the documentation part, assuming @eefahy might be best person to lead the monitoring effort?

**Comment by LynnMcRae** [comment]
I think the technique is to point monitoring to the process' log and look for recent activity, where "recent" can vary.  It's just a DevOps task I think if such a log exists, but some developer involvement if the log needs to exhibit specific behavior it currently does not do. The alternative for apps with an API is to implement the is_it_working response.
